# Makefile of DirecTo6 helper
#
# Author:
# Giovanni Bembo
# Departement of computer engineering
# University of Rome "Tor Vergata"
# Rome, Italy

default:
	gcc -o directo6 ../../common/dirtlib.c ../../common/icmplib.c ../../common/tcpudplib.c tcpudp.c icmp.c translator.c directo6.c
	cp directo6 /sbin
